# Generated by Django 5.2.6 on 2025-09-16 10:25

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_id_alter_product_views'),  # ganti dengan nama migration terakhir sebelum ini
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False, serialize=False
            ),
        ),
    ]
